<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8yPHie\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8yPHie/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8yPHie.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8yPHie\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX8yPHie\App_KernelDevDebugContainer([
    'container.build_hash' => 'X8yPHie',
    'container.build_id' => '27b4ac3c',
    'container.build_time' => 1583223683,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8yPHie');
