<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHx0xQwq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHx0xQwq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHx0xQwq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHx0xQwq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHx0xQwq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Hx0xQwq',
    'container.build_id' => '5db66a13',
    'container.build_time' => 1583250412,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHx0xQwq');
